### ISSUE TITLE
cAER visualizer fails on windows

### ISSUE THREAD

**Issue by federicohyo** [inilabs/caer#50] opened 2017-03-08 10:31 UTC
In windows 10, with mingw64.

Visualizer gives a segmentation fault when more than two windows are opened.

inilabs@DESKTOP-BBC4NNK MINGW64 /home/caer
$ gdb caer-bin.exe
GNU gdb (GDB) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-msys".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ImportError: No module named libstdcxx.v6.printers
/etc/gdbinit:6: Error in sourced command file:
Error while executing Python code.
Reading symbols from caer-bin.exe...done.
(gdb) r
Starting program: /home/caer/caer-bin.exe
[New Thread 8076.0x155c]
[New Thread 8076.0x25a0]
[New Thread 8076.0x864]
[New Thread 8076.0x1030]
2017-03-08 10:30:21: NOTICE: Logger: Initialization successful with log-level 5.
[New Thread 8076.0x2318]
[New Thread 8076.0x19b8]
[New Thread 8076.0x138c]
[New Thread 8076.0x1004]
 - [New Thread 8076.0x1d28]
[New Thread 8076.0x1e0c]
 - [New Thread 8076.0x1968]
 - warning: HEAP[caer-bin.exe]:
warning: HEAP: Free Heap block 00000000026CF890 modified at 00000000026CFA28 aft                                                       er it was freed

Thread 11 received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 8076.0x1968]
0x00007ffff859c4cf in ntdll!RtlpNtMakeTemporaryKey ()
   from /c/Windows/SYSTEM32/ntdll.dll
(gdb) bt ful
#0  0x00007ffff859c4cf in ntdll!RtlpNtMakeTemporaryKey () from /c/Windows/SYSTEM32/ntdll.dll
No symbol table info available.
#1  0x00007ffff84e059a in ntdll!RtlFreeHeap () from /c/Windows/SYSTEM32/ntdll.dll
No symbol table info available.
#2  0x00007ffff84dcfb6 in ntdll!RtlFreeHeap () from /c/Windows/SYSTEM32/ntdll.dll
No symbol table info available.
#3  0x00007ffff8533bf0 in ntdll!EtwEventProviderEnabled () from /c/Windows/SYSTEM32/ntdll.dll
No symbol table info available.
#4  0x00007ffff855df51 in ntdll!memset () from /c/Windows/SYSTEM32/ntdll.dll
No symbol table info available.
#5  0x00007ffff84dcfb6 in ntdll!RtlFreeHeap () from /c/Windows/SYSTEM32/ntdll.dll
No symbol table info available.
#6  0x00007ffff8419dac in msvcrt!free () from /c/Windows/System32/msvcrt.dll
No symbol table info available.
#7  0x00000000671b9dc1 in ?? () from /mingw64/bin/allegro-5.2.dll
No symbol table info available.
#8  0x00000000671b3a18 in ?? () from /mingw64/bin/allegro-5.2.dll
No symbol table info available.
#9  0x00000000671b4131 in ?? () from /mingw64/bin/allegro-5.2.dll
No symbol table info available.
#10 0x00000000671b53bf in ?? () from /mingw64/bin/allegro-5.2.dll
No symbol table info available.
#11 0x0000000067150b75 in ?? () from /mingw64/bin/allegro-5.2.dll
No symbol table info available.
#12 0x000000000041ef11 in caerVisualizerInitGraphics (state=0x2f67e00) at C:/msys64/home/caer/modules/visualizer/visualizer.c:404
No locals.
#13 0x000000000041fd4f in caerVisualizerRenderThread (visualizerState=0x2f67e00)
    at C:/msys64/home/caer/modules/visualizer/visualizer.c:711
        state = 0x2f67e00
#14 0x0000000064944b44 in ?? () from /mingw64/bin/libwinpthread-1.dll
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#15 0x00007ffff843b2ba in msvcrt!_beginthreadex () from /c/Windows/System32/msvcrt.dll
No symbol table info available.
#16 0x00007ffff843b38c in msvcrt!_endthreadex () from /c/Windows/System32/msvcrt.dll
No symbol table info available.
#17 0x00007ffff74d8364 in KERNEL32!BaseThreadInitThunk () from /c/Windows/System32/KERNEL32.DLL
No symbol table info available.
#18 0x00007ffff85070d1 in ntdll!RtlUserThreadStart () from /c/Windows/SYSTEM32/ntdll.dll
No symbol table info available.
#19 0x0000000000000000 in ?? ()
No symbol table info available.
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

It seems to be an allegro related bug..

**Comment by llongi** [comment] 2017-04-30 03:29
Looks like an Allegro/Windows/Graphics Card driver bug. Works here, tested with 4 windows just now.
Closing this, as impossible to reproduce, plus switching visualizer soon.

**Closed by llongi** 2017-04-30 03:29 UTC
