### ISSUE TITLE
FileInput's `autoRestart` causes trouble with monotonic timestamps (eg in Network output)

### ISSUE THREAD

**Issue by breznak** [inilabs/caer#67] opened 2017-04-21 19:36 UTC
`autoRestart` is a (debugging) parameter for `FileInput` (I think it's only applicable there?). 
Obviously this breaks requirement on monotonic timestamps! 

```
            <node name="10-FileInput" path="/1/10-FileInput/">
                <attr key="PacketContainerDelay" type="int">10000</attr>
                <attr key="PacketContainerInterval" type="int">880</attr>
                <attr key="PacketContainerMaxPacketSize" type="int">8192</attr>
                <attr key="autoRestart" type="bool">false</attr>
```

Result: 
- network output complains after the first re-iteration
```
2017-04-21 20:53:25 (TZ+0200): ERROR: 108-NetTCPServerOutput: Detected timestamp going back, expected at least 68086288 but got 4127119. Ignoring packet of type 0 from source 10, with 2 events!
```
- client applications (in case of network output streaming) may break!

Proposed solutions:
- claim that `autoRestart` is only a debug feature and don't care
- send a "Stream Reset" packet at the end of file, and let clients handle the situation
- handle the parameter internally *) 

*) In file input, we can do something like
```
FileInput:
 const size_t fileSizeTime = timestamps[end] - timestamps[0];
 size_t autoResetOffset = 0;
 while (event parsing loop) {
    if(iter==fileSize) {
      autoResetOffset += fileSizeTime;
    }
    event.timestamp += autoResetOffset;
 }
```

What do you think? I like the last approach.
@llongi

**Comment by llongi** [comment] 2017-04-21 20:00
Duplicate of issue #44. The right way to do it is to insert a Timestamp Reset event packet to delimit the stream before and after, exactly how it's handled for device-side resets or resets inside a stream. All clients need to handle that correctly anyway (the Input modules do so). This also triggers the proper resets inside modules.

**Closed by llongi** 2017-04-21 20:00 UTC
